### ISSUE TITLE
One NIC Solution

### ISSUE THREAD

**Issue by stryngs** [stryngs/airpwn-ng#3]
As it stands right now, I am purely limited by what the external toolsets can do with regards to injection.  The backend for the packet injection is done by packit (http://packetfactory.openwall.net/projects/packit/) 0.6.0.  Evidently there is a newer version out, and it just might do the trick, but that has yet to be tested.

If anyone has any ideas about how to inject raw packets in monitor mode, I am all ears...

**Comment by Jack64** [comment]
packit 1.0 works as well :+1:

**Comment by stryngs** [comment]
airtun-ng solves the one NIC issue
