### ISSUE TITLE
Password-Protected Sniffing

### ISSUE THREAD

**Issue by stryngs** [stryngs/airpwn-ng#5]
Search options to allow tcpdump to use a known PSK to sniff packets for monitor mode and send via wep/wpa/wpa2

-- From Jack64

**Comment by stryngs** [comment]
https://github.com/mfontanini/dot11decrypt

-- From Jack64

Initial testing looks very promising, will incorporate tonight

**Comment by stryngs** [comment]
dot11decrypt seems to work well on certain distros, however does not work on Kali...

**Comment by Jack64** [comment]
Fixed -- use built binaries from DEBs folder.
