### ISSUE TITLE
Character Encoding Issues

### ISSUE THREAD

**Issue by Jack64** [stryngs/airpwn-ng#8]
![img_0202](https://cloud.githubusercontent.com/assets/11641285/7336140/b22b45da-ebe4-11e4-8eff-d5df5beb375a.PNG)

Some websites become junk after injection, probably due to character encoding issues. Other websites work fine.
![img_0203](https://cloud.githubusercontent.com/assets/11641285/7336137/8fd44036-ebe4-11e4-9bb1-c18c273fa51a.PNG)

This needs debugging.

**Comment by Jack64** [comment]
It appears this is gzip encoding issue.

**Comment by stryngs** [comment]
Can we account for this somehow?  We can perform deeper filters than just straight GET /.  Perhaps regex to look for gzip or whatever?

**Comment by Jack64** [comment]
Please go to our irc chat !

No dia segunda-feira, 27 de abril de 2015, stryngs <notifications@github.com>
escreveu:

**Comment by Jack64** [comment]
Fixed this by adding the FIN flag and forcing the victim to ignore whatever response comes from the real server.
